name: Deploy Visa Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    # Manual trigger

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: visa-appointment-bot
  REGION: us-central1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # Authentication to GCP
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Set up gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # Enable necessary APIs
    - name: Enable APIs
      run: |
        gcloud services enable cloudbuild.googleapis.com
        gcloud services enable run.googleapis.com
        gcloud services enable containerregistry.googleapis.com

    # Create .gcloudignore file to control what gets uploaded
    - name: Create .gcloudignore
      run: |
        echo ".git
        .github
        .gitignore
        __pycache__
        *.pyc
        .pytest_cache
        .venv
        venv
        env
        .env" > .gcloudignore

    # Build and push to Container Registry directly
    - name: Build and push Docker image
      run: |
        # Configure Docker to use gcloud as a credential helper
        gcloud auth configure-docker
        
        # Build and push using Cloud Build
        gcloud builds submit --tag gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }}
      
    # Deploy the built container
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --set-env-vars="TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }},VISA_EMAIL=${{ secrets.VISA_EMAIL }},VISA_PASSWORD=${{ secrets.VISA_PASSWORD }},SCHEDULE_ID=${{ secrets.SCHEDULE_ID }},COUNTRY_CODE=${{ secrets.COUNTRY_CODE }},VISA_TYPE=${{ secrets.VISA_TYPE }},FACILITY_ID=${{ secrets.FACILITY_ID }},CHECK_INTERVAL=${{ secrets.CHECK_INTERVAL }},MAX_SUBSCRIBERS=${{ secrets.MAX_SUBSCRIBERS }},CHAT_ID=${{ secrets.CHAT_ID }}"

    - name: Show service URL
      run: |
        echo "Deployment completed successfully!"
        echo "Service URL: $(gcloud run services describe $SERVICE_NAME --region $REGION --format='value(status.url)')"