name: Deploy Visa Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    # Manual trigger

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: visa-appointment-bot

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # Authentication to GCP
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Build and deploy to Cloud Run (GCP)
    - name: Set up Artifact Registry repository
      run: |
        gcloud artifacts repositories describe cloud-run-source-deploy \
          --location=us-central1 \
          --format="value(name)" || \
        gcloud artifacts repositories create cloud-run-source-deploy \
          --repository-format=docker \
          --location=us-central1 \
          --description="Docker repository for Cloud Run source deployments"

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: visa-appointment-bot
        region: us-central1
        source: .
        env_vars: |
          TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
          VISA_EMAIL=${{ secrets.VISA_EMAIL }}
          VISA_PASSWORD=${{ secrets.VISA_PASSWORD }}
          SCHEDULE_ID=${{ secrets.SCHEDULE_ID }}
          COUNTRY_CODE=${{ secrets.COUNTRY_CODE }}
          VISA_TYPE=${{ secrets.VISA_TYPE }}
          FACILITY_ID=${{ secrets.FACILITY_ID }}
          CHECK_INTERVAL=${{ secrets.CHECK_INTERVAL }}
          MAX_SUBSCRIBERS=${{ secrets.MAX_SUBSCRIBERS }}
          CHAT_ID=${{ secrets.CHAT_ID }}
    - name: Notify deployment completion
      if: success()
      run: |
        echo "Deployment completed successfully!"