name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1  # Change this to your preferred GCP region
  REPOSITORY: visa-appointment-bot
  
jobs:
  build-and-push:
    name: Build and Push to GCR
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Cloud SDK
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        
    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
        
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud --quiet auth configure-docker us-docker.pkg.dev
        
    - name: Build Docker image
      run: |
        docker build -t us-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/visa-appointment-bot:${{ github.sha }} .
        docker tag us-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/visa-appointment-bot:${{ github.sha }} us-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/visa-appointment-bot:latest
        
    - name: Push Docker image to Artifact Registry
      run: |
        docker push us-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/visa-appointment-bot:${{ github.sha }}
        docker push us-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/visa-appointment-bot:latest
        
    - name: Output Image URI
      id: image-uri
      run: |
        echo "IMAGE_URI=us-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/visa-appointment-bot:${{ github.sha }}" >> $GITHUB_OUTPUT
        
    outputs:
      image_uri: ${{ steps.image-uri.outputs.IMAGE_URI }}