name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1  # Change this to your preferred GCP region
  
jobs:
  build-and-push:
    name: Build and Push to GCR
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        
    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker gcr.io
        
    - name: Build Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/visa-appointment-bot:${{ github.sha }} .
        docker tag gcr.io/$PROJECT_ID/visa-appointment-bot:${{ github.sha }} gcr.io/$PROJECT_ID/visa-appointment-bot:latest
        
    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/$PROJECT_ID/visa-appointment-bot:${{ github.sha }}
        docker push gcr.io/$PROJECT_ID/visa-appointment-bot:latest
        
    - name: Output Image URI
      id: image-uri
      run: |
        echo "IMAGE_URI=gcr.io/$PROJECT_ID/visa-appointment-bot:${{ github.sha }}" >> $GITHUB_OUTPUT
        
    outputs:
      image_uri: ${{ steps.image-uri.outputs.IMAGE_URI }}